[toolchain]
package_manager = "yarn"


[features]
resolution = true
skip-lint = false

[programs.localnet]
calculator = "ATfq4phC8UfQcb5YYbdVp1Z8ohMpRva1rSTPWZVdka8y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
